customadmin/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('/', dashboard, name='dashboard'),
    path('/403', accessdenied, name='403'),
    path('/Banner', banner, name='Banner'),
    path('/Blog', blog, name='Blog'),
    path('/signin', login_page, name='signin'),
    path('/dashboard', dashboard, name='dashboard'),
    path('/Product', products, name='Product'),
    path('/users', users, name='users'),
    path('/Order', orders, name='Order'),
    path('/Link', links, name='Link'),
    path('/Logo', logo, name='Logo'),
    path('/Navbar', navbar, name='Navbar'),
    path('/Widget', widget, name='Widget'),
    path('/Offer', offer, name='Offer'),
    path('/PaymentPartners', paymentPartners, name='PaymentPartners'),
    path('/Policy', policy, name='Policy'),
    path('/WidgetNewsLetter', newsletterWidget, name='WidgetNewsLetter'),
    path('/CheckOutDetails', checkoutDetails, name='CheckOutDetails'),
    path('/Footer', footer, name='Footer'),
    path('/Category', category, name='Category'),
    path('/CartItem', cartitems, name='CartItem'),
    path('/LineItem', lineitems, name='LineItem'),
    path('/Contact', contact, name='Contact'),
    path('/PageSection', pageSection, name='PageSection'),
    path('/About', about, name='About'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce_app.urls')),
    path('myadmin', include('customadmin.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin-page', views.admin_dashboard, name='admin'),
    path('product/<int:product_id>/<slug:product_slug>',views.show_product, name='product_detail'),
    path('cart', views.show_cart, name='show_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('shop', views.shop, name='shop'),
    path('orders', views.orders, name='orders'),
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutPage, name='logout'),
    path('register', views.register, name='register'),
    path('base', views.loadStatic, name='base'),
    path('order/<int:order_id>',views.show_order, name='order_detail'),
    path('about', views.about, name='about'),
    path('blog', views.blog, name='blog'),
    path('blog/<int:blog_id>', views.blog_details, name='blog_details'),
    path('contact', views.contact, name='contact'),
    path('privacy-policy', views.privacy, name='privacy-policy'),
    path('refund-policy', views.refund, name='refund-policy'),
    path('shipping-policy', views.shipping, name='shipping-policy'),
    path('terms-of-service', views.serviceTerms, name='terms-of-service'),
    path('403', views.accessdenied, name='403'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.utils import timezone

class Blog(models.Model):
    title = models.CharField(max_length=191)
    postedBy = models.CharField(max_length=191)
    postedOn = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='blog_images/', blank=True)
    text = models.TextField()

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=191)
    description = models.TextField()

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=191)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, related_name= 'products')
    description = models.TextField()
    shortdes = models.CharField(max_length=191)
    discount = models.IntegerField(default=0)
    sale_price = models.DecimalField(max_digits=7, decimal_places=2 ,default= 0.0)
    image = models.ImageField(upload_to='products_images/', blank=True)
    stock = models.IntegerField(default= 10)
    feature_product = models.BooleanField(default = False)

    def __str__(self):
        return self.name

class CartItem(models.Model):
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def set_user(self, user):
        self.user = user

    def __str__(self):
        return "{}:{}".format(self.product.name, self.id)

    def update_quantity(self, quantity):
        self.quantity = self.quantity + quantity
        self.save()

    def total_cost(self):
        return self.quantity * self.price

class CheckOutDetails(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name= 'checkout_details')
    first_name = models.CharField(max_length=191)
    last_name = models.CharField(max_length=191)
    email = models.EmailField()
    address = models.CharField(max_length=191)
    city = models.CharField(max_length=255)
    country = CountryField()
    zip_code = models.CharField(max_length=20)
    phn = models.CharField(max_length=20)

class Order(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    payment_status = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_note = models.TextField(blank= True, null= True ,  default="")

    class PaymentMethod(models.TextChoices):
        COD = 'cd', 'Cash On Delivery'
        CREDIT_CARD = 'cc', 'Credit Card'
        DEBIT_CARD = 'dc', 'Debit Card'
        PAYPAL = 'pp', 'PayPal'
        STRIPE = 'st', 'Stripe'
        APPLE_PAY = 'ap', 'Apple Pay'
        GOOGLE_PAY = 'gp', 'Google Pay'
        UPI = 'up', 'UPI'

    payment_method = models.CharField(max_length=2, choices=PaymentMethod.choices)

    def set_user(self, user):
        self.user = user

    def __str__(self):
        return "{}:{}".format(self.id, self.user)

    def total_cost(self):
        return sum([li.cost() for li in self.lineitem_set.all()])


class LineItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}:{}".format(self.product.name, self.id)

    def cost(self):
        return self.price * self.quantity


class Logo(models.Model):
    logo = models.ImageField(upload_to='logo/', blank=True)
    logo_url = models.CharField(max_length=255)

class Link(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255)

    def __str__(self):
        return self.name + ":" + self.url

class Navbar(models.Model):
    logo = models.OneToOneField(Logo, on_delete=models.PROTECT, related_name= 'nav_bar')
    links = models.ManyToManyField(Link)

class Widget(models.Model):
    heading = models.CharField(max_length=10)
    links = models.ManyToManyField(Link)

class WidgetNewsLetter(models.Model):
    heading = models.CharField(max_length=10)
    text = models.CharField(max_length=255, null=True, blank=True)

class Footer(models.Model):
    logo = models.OneToOneField(Logo, on_delete=models.PROTECT, related_name= 'footer')
    moto = models.CharField(max_length=255)
    widgets = models.ManyToManyField('Widget', related_name='footer')
    payment_partners = models.ManyToManyField('PaymentPartners', related_name='footer')
    news_letter = models.OneToOneField(WidgetNewsLetter, on_delete=models.PROTECT, related_name= 'footer')
    footer_text = models.TextField( default="Copyright © 2023 All rights reserved | This template is made with <3 by Colorlib")

class PaymentPartners(models.Model):
    url = models.CharField(max_length=255)
    partner = models.ImageField(upload_to='payment_partners/', blank=True, null=True)

class Policy(models.Model):
    title = models.CharField(max_length=100)
    policyName = models.CharField(unique=True, max_length = 100)
    text = models.TextField()

class Banner(models.Model):
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    text = models.TextField()
    image = models.ImageField(upload_to='banners/', blank=True, null=True)

class Contact(models.Model):
    title = models.CharField(max_length=255)
    map = models.CharField(max_length=1000, null= True, blank= True)
    text = models.TextField()

class PageSection(models.Model):
    text = models.TextField()

class About(models.Model):
    title = models.CharField(max_length=255)
    sections = models.ManyToManyField(PageSection, related_name= 'About')

class Offer(models.Model):
    name = models.CharField(max_length=255)
    product = models.OneToOneField(Product, on_delete=models.CASCADE, related_name= 'offer')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()
    on_display = models.BooleanField(unique=True, default=False)

    def is_active(self):
        return timezone.now() < self.expiration

    def time_remaining(self):
        return (self.expiration - timezone.now()).total_seconds() * 1000

    def delete_if_expired(self):
        if not self.is_active():
            self.delete()

ecommerce_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *

class Filter(forms.Form):
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple)
    min_price = forms.DecimalField(max_digits=10, decimal_places=2)
    max_price = forms.DecimalField(max_digits=10, decimal_places=2)

class CartForm(forms.Form):
    quantity = forms.IntegerField(initial='1')
    product_id = forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(CartForm, self).__init__(*args, **kwargs)


class CheckOutForm(forms.ModelForm):
    class Meta:
        model = CheckOutDetails
        fields = '__all__'
        exclude = ('user','id')

class PayMentForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('payment_method','order_note')

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

ecommerce_app/templates/cart.html
{% extends 'base.html' %}

{% block title %} My Cart {% endblock %}
{% load static %}
{% block content %}

<!-- Breadcrumb Section Begin -->
<style>
    .alert {
        padding: 20px;
        background-color: #F3F2EE;
        color: rgb(0, 0, 0);
    }

    .closebtn {
        margin-left: 15px;
        color: black;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
    }

    .closebtn:hover {
        color: black;
    }

    #id_order_note{
        width: 100%;
        height: 50px;
    }
    .nice-select{
        width: 100%;
    }
    #close{
        margin-top: -4px;
    }
    #pop{
        margin-bottom: 20px;
    }
    .spad {
        padding-top: 50px;
        padding-bottom: 100px;
    }
</style>
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Shopping Cart</h4>
                    <div class="breadcrumb__links">
                        <a href="/">Home</a>
                        <a href="/shop">Shop</a>
                        <span>Shopping Cart</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Shopping Cart Section Begin -->
<section class="shopping-cart spad">
    <div class="container">
        {% for message in messages %}
        <div class="coupon__code" id="pop">
            <div class="closebtn" id="close" onclick="this.parentElement.style.visibility='hidden';">&times;</div>
            <span class="icon_check_alt"></span>{{message}}
        </div>
        {% endfor %}
        <div class="row">
            <div class="col-lg-8">
                <div class="shopping__cart__table">
                    {% if cart_item_count %}
                    <table>
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th></th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                            <tr>
                                <td class="product__cart__item">
                                    <div class="product__cart__item__pic">
                                        <img style="width: 100px; height: 100px;" src="/media/{{item.product.image}}" alt="">
                                    </div>
                                    <div class="product__cart__item__text">
                                        <h6>{{ item.product.name }}</h6>
                                        <h5>${{ item.price }}</h5>
                                    </div>
                                </td>
                                <td class="quantity__item">
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <div class="quantity">
                                            <div class="pro-qty-2">
                                                <input type="text" name="quantity" value="{{ item.quantity }}">
                                            </div>
                                        </div>
                                </td>

                                <td class="quantity__item">
                                    <button type="submit" class="rounded-circle border-0 btn"
                                        style="background-color: #F3F2EE;" name="submit" value="Update"><i
                                            class="fa fa-pencil"></i></button>
                                    <input type="hidden" name="item_id" value="{{ item.id }}">
                                    </form>
                                </td>
                                <td class="cart__price">$ {{ item.total_cost }}</td>
                                <td class="cart__close">
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="item_id" value="{{ item.id }}">
                                        <button class="rounded-circle border-0 btn" type="submit" name="submit"
                                            value="Remove"><i class="fa fa-close"></i></button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p>Cart Empty</p>
                    {% endif %}
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="continue__btn">
                            <a href="{% url 'index' %}">Continue Shopping</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart__discount">
                    <!-- <h6>Discount codes</h6>
                    <form action="#">
                        <input type="text" placeholder="Coupon code">
                        <button type="submit">Apply</button>
                    </form> -->
                </div>
                <div class="cart__total">
                    <h6>Cart total</h6>
                    <ul>
                        <li>Subtotal <span> ${{ cart_subtotal }}</span></li>
                        <li>Total <span> ${{ cart_subtotal }}</span></li>
                    </ul>
                    <a href="{% url 'checkout' %}" class="primary-btn">Proceed to checkout</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shopping Cart Section End -->

{% endblock %}

ecommerce_app/templates/order-details.html
{% extends 'base.html' %}

{% block title %} Order {% endblock %}
{% load static %}
{% load countries %}
{% block content %}

<!-- Breadcrumb Section Begin -->
<link href="{%  static 'css/custom.css' %}" type="text/css">
<style>
    .alert {
        padding: 20px;
        background-color: #F3F2EE;
        color: rgb(0, 0, 0);
    }

    .closebtn {
        margin-left: 15px;
        color: black;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
    }

    .closebtn:hover {
        color: black;
    }

    #id_order_note{
        width: 100%;
        height: 50px;
    }
    .nice-select{
        width: 100%;
    }
    #close{
        margin-top: -4px;
    }
    #pop{
        margin-bottom: 20px;
    }
    .spad {
        padding-top: 50px;
        padding-bottom: 100px;
    }
    .order-products-link, .order-products-link:hover{
        text-decoration: none;
        color: black;
    }
</style>
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Order #456{{order.id}}</h4>
                    <div class="breadcrumb__links">
                        <a href="/">Home</a>
                        <a href="/orders">Orders</a>
                        <span>Order</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Checkout Section Begin -->
<section class="checkout spad">
    <div class="container">
        {% for message in messages %}
        <div class="coupon__code" id="pop">
            <div class="closebtn" id="close" onclick="this.parentElement.style.visibility='hidden';">&times;</div>
            <span class="icon_check_alt"></span>{{message}}
        </div>
        {% endfor %}

        {% for field in userForm %}
            {% for error in field.errors %}
                <div class="alert" style="background-color: red; color: #F3F2EE;">
                    <span class="closebtn" onclick="this.parentElement.style.visibility='hidden';">&times;</span>
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endfor %}
        <div class="checkout__form">

                <div class="row">
                    <div class="col-lg-8 col-md-6">
                        <!-- <h6 class="coupon__code"><span class="icon_tag_alt"></span> Have a coupon? <a href="#">Click
                                here</a> to enter your code</h6> -->
                        <h6 class="checkout__title">Billing Details</h6>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>{{form.first_name.label}}<span>*</span></p>
                                    {{form.first_name}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>{{form.last_name.label}}<span>*</span></p>
                                    {{form.last_name}}
                                </div>
                            </div>
                        </div>

                        <div class="checkout__input">
                            <p>{{form.address.label}}<span>*</span></p>
                            {{form.address}}
                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Country<span>*</span></p>
                                    <input type="text" value="{{form.country.value.name }}">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>{{form.city.label}}<span>*</span></p>
                                    {{form.city}}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>{{form.zip_code.label}}<span>*</span></p>
                                    {{form.zip_code}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Mode of Payment<span>*</span></p>
                                    <input value="{{order.get_payment_method_display}}" >
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>{{form.phn.label}}<span>*</span></p>
                                    {{form.phn}}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>{{form.email.label}}<span>*</span></p>
                                    {{form.email}}
                                </div>
                            </div>
                        </div>
                        {% if order.order_note %}
                            <div class="checkout__input">
                                <p>Note about your order, e.g, special note for delivery<span>*</span></p>
                                {{order.order_note}}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="checkout__order">
                            <h4 class="order__title">Your order</h4>
                            <div class="checkout__order__products">Product <span>Total</span></div>
                            <ul class="checkout__total__products">
                            {% for item in order.lineitem_set.all %}
                                <li>0{{ forloop.counter }}. <a class="order-products-link" href="{% url 'product_detail' item.product.pk item.product.slug %}">{{item.product.name}}</a> &times; {{item.quantity}} <span>$ {{ item.cost }}</span></li>
                            {% endfor %}
                            </ul>
                            <ul class="checkout__total__all">
                                <li>Subtotal <span> ${{ order.total_cost }}</span></li>
                                <li>Total <span> ${{ order.total_cost }}</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
<script>
    $(document).ready(function() {
        $('.checkout__form :input').prop('readonly', true);
    });
    </script>
<!-- Checkout Section End -->

{% endblock %}

ecommerce_app/templates/shop.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Male-Fashion {% endblock %}

{% block style %}

<style>
    /* Chrome, Safari, Edge, Opera */
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }

    /* Firefox */
    input[type=number] {
      -moz-appearance: textfield;
    }

    #id_min_price, #id_max_price{
        width: 50px;
    }
    #price_div{
        margin: 5px;
    }
</style>

{% endblock %}

{% block content %}
<!-- Header Section End -->

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Shop</h4>
                    <div class="breadcrumb__links">
                        <a href="/">Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Shop Section Begin -->
<section class="shop spad">
    <div class="container">
        <div class="row">
            {% include 'filter.html' %}
            <div class="col-lg-9">
                <div class="shop__product__option">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="shop__product__option__left">
                                <p>Showing 1–12 of 126 results</p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="shop__product__option__right">
                                <p>Sort by Price:</p>
                                <select>
                                    <option value="">Low To High</option>
                                    <option value="">$0 - $55</option>
                                    <option value="">$55 - $100</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">

                    {% for product in all_products %}

                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="product__item">

                                <div class="product__item__pic set-bg"
                                    data-setbg=/media/{{product.image}}>
                                    <ul class="product__hover">
                                        <li><a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a></li>
                                        <li><a href="#"><img src="{% static 'img/icon/compare.png' %}" alt="">
                                                <span>Compare</span></a>
                                        </li>
                                        <li><a href="{% url 'product_detail' product.pk product.slug %}"><img src="{% static 'img/icon/search.png' %}" alt=""></a></li>

                                    </ul>
                                </div>

                            <div class="product__item__text">
                                <h6>{{ product.name }}</h6>
                                <a href="#" class="add-cart">+ Add To Cart</a>
                                <div class="rating">
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                </div>
                                <h5>${{ product.price }}</h5>
                                <div class="product__color__select">
                                    <label for="pc-4">
                                        <input type="radio" id="pc-4">
                                    </label>
                                    <label class="active black" for="pc-5">
                                        <input type="radio" id="pc-5">
                                    </label>
                                    <label class="grey" for="pc-6">
                                        <input type="radio" id="pc-6">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product__pagination">
                            <a class="active" href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <span>...</span>
                            <a href="#">21</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shop Section End -->

{% endblock %}

{% block javascript %}
<script>

    $(document).ready(function() {
      $('#filter input').change(function() {
        $('#filter').submit();
      });
    });

    $(function() {
      var sliderRange = $("#slider-range");
      var priceMin = $("#id_min_price");
      var priceMax = $("#id_max_price");

      sliderRange.slider({
        range: true,
        min: 0,
        max: 1000,
        values: [0, 1000],
        slide: function(event, ui) {
          priceMin.val(ui.values[0]);
          priceMax.val(ui.values[1]);
        }
      });

      // Set initial values
      priceMin.val(sliderRange.slider("values", 0));
      priceMax.val(sliderRange.slider("values", 1));
    });
</script>
{% endblock %}